import './style.css'

type HeroKind = 'flare'|'moss'|'luma'|'thorn'|'aqua'|'nova'|'volt'
type Hero = {kind:HeroKind; row:number; col:number; hp:number; cd:number; el:HTMLElement}
type Enemy = {kind:'scout'|'crusher'|'glider'|'boss'; row:number; x:number; hp:number; speed:number; bite:number; reward:number; stunUntil:number; el:HTMLElement}
type HeroDef = {kind:HeroKind; name:string; cost:number; glyph:string; role:string; description:string; hp:number; cooldown:number; locked?:boolean; unlock?:number; radianceUnlock?:number}
const defs:HeroDef[] = [
  {kind:'flare',name:'Fire Cannon',cost:50,glyph:'●',role:'FIRE',description:'Rapid, low-damage fire shells in one lane.',hp:130,cooldown:1.1},
  {kind:'moss',name:'Shield Barrier',cost:75,glyph:'⬢',role:'SHIELD',description:'A defensive energy wall. It cannot shoot.',hp:350,cooldown:99},
  {kind:'luma',name:'Pulse Generator',cost:25,glyph:'◉',role:'ENERGY',description:'Creates 20 energy every 5 seconds.',hp:90,cooldown:5},
  {kind:'thorn',name:'Venom Cannon',cost:100,glyph:'✦',role:'POISON',description:'Slow shots with heavy poison damage.',hp:130,cooldown:2.25},
  {kind:'aqua',name:'Frost Cannon',cost:125,glyph:'❄',role:'FROST',description:'Low damage frost shots that slow aliens.',hp:115,cooldown:1.5},
  {kind:'nova',name:'Meteor Cannon',cost:175,glyph:'☄',role:'ULTIMATE',description:'Calls a devastating meteor onto its closest target.',hp:140,cooldown:7.5,locked:true,unlock:1300},
  {kind:'volt',name:'Storm Cannon',cost:150,glyph:'ϟ',role:'CHAIN',description:'Electric bolts shock the target and a second alien.',hp:120,cooldown:2.2,locked:true,unlock:750},
]
const $ = <T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!
let coins=Number(localStorage.getItem('bloomfall-coins')||'80'), unlocked:HeroKind[] = JSON.parse(localStorage.getItem('bloomfall-unlocked')||'["flare","moss","luma","thorn"]'), savedWave=Number(localStorage.getItem('voidfront-saved-wave')||'1')
;(['flare','moss','luma','thorn','aqua'] as HeroKind[]).forEach(kind=>{if(!unlocked.includes(kind))unlocked.push(kind)})
localStorage.setItem('bloomfall-unlocked',JSON.stringify(unlocked))
let selected:HeroKind|null=null, radiance=175, wave=1, kills=0, waveCoins=0, toSpawn=0, spawned=0, spawnClock=0, running=false, paused=false, core=100, heroes:Hero[]=[], enemies:Enemy[]=[], raf=0, shopReturn='home', invasionWarning=false, invasionWarningShown=false, invasionWarningUntil=0
let gridColumns=9
const reloadUntil:Partial<Record<HeroKind,number>>={}
const usesPhoneBoard=()=>window.matchMedia('(max-width: 600px), (max-height: 500px) and (pointer: coarse)').matches

$('#app')!.innerHTML=`<main class="app">
 <section id="home" class="screen home-screen">
  <nav><a class="logo"><i>✦</i> VOID<span>FRONT</span></a><div class="nav-menu"><button data-codex="guardians">UNITS</button><button data-codex="enemies">ALIEN INTEL</button><button data-codex="story">TRANSMISSION</button><button id="openShop">SHOP</button></div><div class="nav-right"><button class="coin-pill" id="homeCoins">◈ 0</button><button class="sound">♫</button></div></nav>
  <div class="home-hero"><div class="story"><p class="overline">BASE KHEPRI-9 · ALIEN ATTACK</p><h1>Aliens are here.<br><em>Defend</em> the base.</h1><p>Alien ships are attacking your base. Build cannons, stop the aliens, and keep the rescue beacon safe until help arrives.</p><div class="home-buttons"><button class="play-btn" id="startGame">NEW DEFENSE <b>→</b></button><button class="ghost-btn" id="resumeGame">RESUME WAVE <span id="resumeWave">01</span></button><button class="ghost-btn" id="openShopAlt">CANNON SHOP <span>◈</span></button></div><div class="progress-note"><span>✦</span><div><b>KHEPRI-9 RESCUE BEACON</b><small>Goal: survive the waves · earn credits · unlock cannons</small></div></div></div>
   <div class="home-art"><div class="moon"></div><div class="alien-ship"><i></i><i></i><i></i><b></b></div><div class="mountain m1"></div><div class="mountain m2"></div><div class="beacon"><div class="beacon-light">✦</div><div class="beacon-tower"></div></div><div class="hero-sil h1s">✦</div><div class="hero-sil h2s">◒</div><div class="hero-sil h3s">✧</div><div class="battle-squad"><i class="mini-cannon fire"></i><i class="mini-cannon frost"></i><i class="mini-cannon venom"></i><i class="mini-cannon shield"></i><i class="mini-cannon fire c5"></i><b class="mini-alien a1"></b><b class="mini-alien a2"></b><b class="mini-alien a3"></b><b class="mini-alien a4"></b><b class="mini-alien a5"></b><b class="mini-alien a6"></b></div><div class="home-cannon"><i></i><b></b><span></span></div><div class="plasma-shot"></div><div class="home-blast"><i></i><i></i><i></i></div><div class="home-enemy">◇</div></div></div>
  <div class="home-footer"><span>★ YOUR GARDEN AWAITS</span><span>COLLECT COINS · UNLOCK GUARDIANS · DEFEND THE GROVE</span><span>v1.1.0</span></div>
 </section>
 <section id="game" class="screen game-screen hidden"><header class="game-top"><button class="back" id="quitGame">‹</button><div class="game-title"><small>RELAY STATION KHEPRI-9</small><b>Defense Grid Alpha</b></div><div class="objective"><span>RELAY INTEGRITY</span><div><i id="coreBar"></i></div><b id="coreText">100%</b></div><button class="pause" id="pauseBtn">Ⅱ</button></header>
  <section class="battle-head"><div><p class="overline" id="waveType">WAVE 01</p><h2 id="waveTitle">Incoming Signal</h2><p id="waveCopy">Alien contacts approaching the base.</p></div><div class="wave-badge"><small>WAVE</small><b id="waveNo">1</b><span>/ 30</span></div><div id="invasionTimer" class="invasion-timer"><b id="setupCount">15</b><span>INCOMING</span></div></section>
  <section class="deck"><div class="radiance"><span>✧</span><b id="radiance">175</b><small>RADIANCE</small></div><div id="heroCards" class="hero-cards"></div><label class="unit-picker">ACTIVE UNIT<select id="unitPicker"></select></label><div class="defeated"><small>DEFEATED</small><b id="kills">0</b><span>/ <i id="total">0</i></span></div></section>
  <section class="arena-wrap"><aside class="lane-numbers"><i>01</i><i>02</i><i>03</i><i>04</i><i>05</i></aside><div id="arena" class="arena"></div><aside class="beacon-edge"><span>✦</span><small>THE<br>BEACON</small></aside><div id="hint" class="hint"></div></section><div id="invasionAlert" class="invasion-alert hidden">ALIENS ARE COMING</div>
 </section>
  <section id="intermission" class="screen modal-screen hidden"><div class="modal-card reward"><p class="overline">SECTOR SECURED</p><div class="reward-star">✦</div><h2 id="rewardTitle">Wave Complete!</h2><p id="rewardText">The alien vanguard falls back into the dust storm.</p><div class="reward-row"><div><span>◈</span><b id="rewardCoins">+0</b><small>CREDITS RECOVERED</small></div><div><span>✧</span><b id="rewardKills">0</b><small>ARKANTH ELIMINATED</small></div></div><div class="modal-actions"><button class="ghost-btn" id="waveHome">HOME</button><button class="ghost-btn" id="saveProgress">SAVE</button><button class="ghost-btn" id="rewardShop">SHOP</button><button class="play-btn" id="nextWave">PREPARE NEXT WAVE <b>→</b></button></div><small id="saveNotice" class="modal-tip">Command tip: deploy Reactor Nodes early to keep your grid charged.</small></div></section>
 <section id="shop" class="screen modal-screen hidden"><div class="modal-card shop-card"><button class="close" id="closeShop">×</button><p class="overline">KHEPRI-9 ARMORY</p><h2>Authorize new hardware.</h2><p>Recover credits from fallen aliens. Every unit you authorize remains in your loadout for future defenses.</p><div class="shop-balance">YOUR CREDITS <b id="shopCoins">0</b><span>◈</span></div><div id="shopItems" class="shop-items"></div></div></section>
 <section id="codex" class="screen modal-screen hidden"><div class="modal-card codex-card"><button class="close" id="closeCodex">×</button><p class="overline" id="codexOverline">FIELD INTELLIGENCE</p><h2 id="codexTitle">The defense roster.</h2><div id="codexContent"></div></div></section>
 <section id="lose" class="screen modal-screen hidden"><div class="modal-card result"><p class="overline">THE BEACON FELL</p><h2>The garden will grow again.</h2><p>You kept the light alive long enough to learn. Rebuild your line and defend the Grove once more.</p><button class="play-btn" id="tryAgain">TRY AGAIN <b>↻</b></button><button class="text-btn" id="returnHome">RETURN HOME</button></div></section>
</main>`

function save(){localStorage.setItem('bloomfall-coins',String(coins));localStorage.setItem('bloomfall-unlocked',JSON.stringify(unlocked))}
function show(id:string){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$('#'+id).classList.remove('hidden'); updateAll()}
function waveInfo(){const boss=wave%3===0,count=wave===1?4:4+Math.ceil(wave*1.25);return boss?{name:'BOSS LEVEL',copy:'A Hive Colossus is leading the attack. Destroy it before it tears through the defense grid.',count,boss}:{name:wave===1?'First Contact':wave===2?'Hive Pressure':`Swarm Assault ${wave}`,copy:wave===1?'Only a few slow scouts are approaching. Use this wave to build your first line.':`The swarm is growing steadily. Build your defense and prepare for tougher aliens.`,count,boss:false}}
function updateAll(){ $('#homeCoins').textContent=`◈ ${coins}`;$('#shopCoins').textContent=String(coins);$('#resumeWave').textContent=String(savedWave).padStart(2,'0'); $('#radiance').textContent=String(radiance);$('#waveNo').textContent=String(wave);$('#kills').textContent=String(kills);$('#total').textContent=String(toSpawn);$('#coreText').textContent=`${Math.max(0,Math.ceil(core))}%`;$('#coreBar').style.width=`${Math.max(0,core)}%`;const preparing=running&&spawned===0&&spawnClock>0;$('#invasionTimer').classList.toggle('hidden',!preparing);$('#setupCount').textContent=String(Math.ceil(Math.max(0,spawnClock)));$('#invasionAlert').classList.toggle('hidden',!invasionWarning); const info=waveInfo();$('#waveTitle').textContent=info.name;$('#waveTitle').classList.toggle('boss-title',info.boss);$('#waveCopy').textContent=info.copy;$('#waveType').textContent=info.boss?'⚠ BOSS LEVEL ⚠':`WAVE ${String(wave).padStart(2,'0')}`;$('#waveType').classList.toggle('boss-label',info.boss);renderShop()}
function selectUnit(kind:HeroKind){selected=kind;renderCards();hint(`${defs.find(d=>d.kind===kind)!.name} selected`)}
function updateReloadCard(kind:HeroKind){const button=document.querySelector<HTMLButtonElement>(`.hero-card[data-kind="${kind}"]`),until=reloadUntil[kind];if(!button||!until)return;const remaining=Math.max(0,until-Date.now());if(remaining===0){delete reloadUntil[kind];button.disabled=false;button.classList.remove('reloading');button.querySelector('.reload-ring')?.remove();return}button.disabled=true;button.classList.add('reloading');let ring=button.querySelector<HTMLElement>('.reload-ring');if(!ring){ring=document.createElement('span');ring.className='reload-ring';button.append(ring)}ring.style.setProperty('--load',`${100-(remaining/5000)*100}%`);ring.textContent=String(Math.ceil(remaining/1000));setTimeout(()=>updateReloadCard(kind),100)}
function startReload(kind:HeroKind){reloadUntil[kind]=Date.now()+5000;updateReloadCard(kind)}
function renderCards(){const card=$('#heroCards'),picker=$('#unitPicker') as HTMLSelectElement;card.innerHTML='';const available=defs.filter(d=>unlocked.includes(d.kind));picker.innerHTML=`<option value="">Choose cannon…</option>`+available.map(d=>`<option value="${d.kind}" ${selected===d.kind?'selected':''}>${d.name}</option>`).join('');available.forEach(d=>card.insertAdjacentHTML('beforeend',`<button type="button" data-kind="${d.kind}" class="hero-card ${selected===d.kind?'chosen':''}" aria-pressed="${selected===d.kind}"><span class="card-icon ${d.kind}">${d.glyph}</span><span><b>${d.name}</b><small>${d.role}</small></span><em>✧ ${d.cost}</em></button>`));card.querySelectorAll<HTMLButtonElement>('.hero-card').forEach(button=>button.onclick=event=>{event.stopPropagation();const kind=button.dataset.kind as HeroKind;if((reloadUntil[kind]||0)>Date.now())return hint('That cannon is reloading.');selectUnit(kind)});available.forEach(d=>updateReloadCard(d.kind))}
function renderShop(){const wrap=$('#shopItems');wrap.innerHTML='';defs.filter(d=>d.locked).forEach(d=>{const got=unlocked.includes(d.kind);wrap.insertAdjacentHTML('beforeend',`<div class="shop-item ${got?'owned':''}"><div class="shop-glyph ${d.kind}">${d.glyph}</div><div><b>${d.name}</b><span>${d.role}</span><p>${d.description}</p></div><button data-unlock="${d.kind}" ${got?'disabled':''}>${got?'UNLOCKED':`BUY · ◈ ${d.unlock}`}</button></div>`)});}
function makeGrid(){const arena=$('#arena');gridColumns=usesPhoneBoard()?6:9;arena.innerHTML='';for(let r=0;r<5;r++)for(let c=0;c<gridColumns;c++){const plot=document.createElement('button');plot.className=`plot r${r} c${c}`;plot.dataset.r=String(r);plot.dataset.c=String(c);plot.ariaLabel='Place cannon';plot.style.left=`${c*100/gridColumns}%`;plot.style.width=`${100/gridColumns}%`;arena.append(plot)}}
function hint(text:string){const h=$('#hint');h.textContent=text;h.classList.add('visible');setTimeout(()=>h.classList.remove('visible'),1800)}
function startExpedition(){cancelAnimationFrame(raf);wave=1;startWave()}
function resumeExpedition(){cancelAnimationFrame(raf);wave=Math.min(30,Math.max(1,savedWave));startWave()}
function saveProgress(){savedWave=wave>=30?30:wave+1;localStorage.setItem('voidfront-saved-wave',String(savedWave));save();$('#saveNotice').textContent=`✓ Saved! You will resume on Wave ${savedWave}.`;$('#saveNotice').classList.add('saved')}
function startWave(){const info=waveInfo();radiance=150+Math.min(75,(wave-1)*3);kills=0;waveCoins=0;toSpawn=info.count;spawned=0;spawnClock=15;invasionWarning=false;invasionWarningShown=false;invasionWarningUntil=0;core=100;heroes=[];enemies=[];selected=null;running=true;paused=false;makeGrid();show('game');renderCards();hint('15-second setup phase: build a strong line before the aliens arrive.');tick()}
function plant(r:number,c:number){if(!running||paused)return; if(!selected)return hint('Choose a cannon first.');if(heroes.some(h=>h.row===r&&h.col===c))return hint('That pad already has a cannon.');const d=defs.find(x=>x.kind===selected)!;if((reloadUntil[d.kind]||0)>Date.now())return hint(`${d.name} is reloading.`);if(radiance<d.cost)return hint('Not enough energy. Build a Pulse Generator.');radiance-=d.cost;const el=document.createElement('div');el.className=`guardian ${d.kind}`;el.dataset.kind=d.kind;const visual=d.kind==='moss'?`<div class="shield-wall"><span>SHIELD</span><i></i><i></i><i></i></div>`:d.kind==='aqua'?`<div class="frost-crystal">❄</div><div class="frost-nozzle"></div>`:d.kind==='thorn'?`<div class="venom-tank"><i></i></div><div class="venom-barrel"></div>`:`<div class="cannon-base"></div><div class="cannon-core">${d.glyph}</div><div class="cannon-barrel"></div>`;el.innerHTML=`<div class="unit-hp"><i></i><b>${d.hp}</b></div>${visual}`;$('#arena').append(el);const hero:Hero={kind:d.kind,row:r,col:c,hp:d.hp,cd:.4,el};heroes.push(hero);placeHero(hero);startReload(d.kind);updateAll()}
function placeHero(h:Hero){const columnWidth=100/gridColumns,offset=gridColumns===6?.5:2;h.el.style.left=`calc(${h.col*columnWidth}% + ${offset}%)`;h.el.style.top=`calc(${h.row*20}% + 3.1%)`}
function spawn(){const roll=Math.random();let kind:Enemy['kind']='scout';if(wave%3===0&&spawned===toSpawn-1)kind='boss';else if(wave>=2&&roll>.55)kind='crusher';else if(wave>=3&&roll>.82)kind='glider';const values:Record<Enemy['kind'],[number,number,number,number]>={scout:[60+wave*6,.04+wave*.0024,4+wave*.8,10+wave*2],crusher:[120+wave*16,.022+wave*.0015,8+wave*1.35,25+wave*3],glider:[76+wave*11,.052+wave*.0025,6+wave*1.25,20+wave*3],boss:[360+wave*140,.018+wave*.0013,18+wave*4,260+wave*35]};const stats=values[kind],row=Math.floor(Math.random()*5),el=document.createElement('div');el.className=`enemy ${kind}`;el.style.top=`calc(${row*20}% + 2.5%)`;el.innerHTML=`<div class="enemy-hp"><i></i><b>${stats[0]}</b></div><div class="alien-head"><i></i><i></i><b></b></div><div class="alien-body"><span></span><span></span></div><div class="alien-legs"></div>`;$('#arena').append(el);enemies.push({kind,row,x:102,hp:stats[0],speed:stats[1],bite:stats[2],reward:stats[3],stunUntil:0,el});}
function hurt(e:Enemy,amount:number,slow=false){e.hp-=amount;if(slow){e.speed=Math.max(.022,e.speed*.62);e.el.classList.add('wet')}e.el.classList.add('hit');setTimeout(()=>e.el.classList.remove('hit'),130);const max=e.kind==='scout'?60+wave*6:e.kind==='crusher'?120+wave*16:e.kind==='glider'?76+wave*11:360+wave*140;const bar=e.el.querySelector<HTMLElement>('.enemy-hp i')!,label=e.el.querySelector<HTMLElement>('.enemy-hp b')!;bar.style.width=`${Math.max(0,e.hp/max)*100}%`;label.textContent=String(Math.max(0,Math.ceil(e.hp)))}
function hurtHero(h:Hero,amount:number){h.hp-=amount;const max=defs.find(d=>d.kind===h.kind)!.hp,bar=h.el.querySelector<HTMLElement>('.unit-hp i')!,label=h.el.querySelector<HTMLElement>('.unit-hp b')!;bar.style.width=`${Math.max(0,h.hp/max)*100}%`;label.textContent=String(Math.max(0,Math.ceil(h.hp)));h.el.classList.add('under-attack');setTimeout(()=>h.el.classList.remove('under-attack'),130)}
function fireShot(h:Hero,target:Enemy,amount:number,slow=false){if(!enemies.includes(target))return;const p=document.createElement('i'),columnWidth=100/gridColumns,start=h.col*columnWidth+columnWidth*.63; p.className=`shot ${h.kind}`;p.style.left=`${start}%`;p.style.top=`calc(${h.row*20}% + 10%)`;$('#arena').append(p);const distance=Math.max(20,(target.x-start)*$('#arena').clientWidth/100);hurt(target,amount,slow);const animation=p.animate([{transform:'translateX(0) scale(1)'},{transform:`translateX(${distance}px) scale(.55)`}],{duration:Math.min(520,140+distance*.55),easing:'linear'});animation.finished.then(()=>p.remove())}
function stunEnemy(e:Enemy){e.stunUntil=Date.now()+3000;e.el.classList.add('stunned');setTimeout(()=>{if(Date.now()>=e.stunUntil)e.el.classList.remove('stunned')},3050)}
function projectile(h:Hero,target:Enemy){if(h.kind==='luma'){radiance+=25;hint('+25 energy');return}target.el.classList.add('targeted');setTimeout(()=>target.el.classList.remove('targeted'),260);if(h.kind==='nova'){fireShot(h,target,260);const blast=document.createElement('i');blast.className='orbital-blast';blast.style.left=`${target.x}%`;blast.style.top=`calc(${target.row*20}% + 8%)`;$('#arena').append(blast);setTimeout(()=>blast.remove(),400);return}if(h.kind==='volt'){fireShot(h,target,44);stunEnemy(target);return}if(h.kind==='thorn'){fireShot(h,target,48);return}if(h.kind==='aqua'){fireShot(h,target,15,true);return}fireShot(h,target,11)}
function killEnemy(e:Enemy){e.el.classList.add('vanish');setTimeout(()=>e.el.remove(),200);enemies.splice(enemies.indexOf(e),1);kills++;waveCoins+=e.reward;coins+=e.reward;save()}
function closestEnemy(h:Hero){return enemies.filter(e=>e.row===h.row&&e.x>h.col*100/gridColumns).sort((a,b)=>a.x-b.x)[0]}
function firstCannon(e:Enemy){return heroes.filter(h=>h.row===e.row&&h.col*100/gridColumns<e.x).sort((a,b)=>b.col-a.col)[0]}
function tick(){if(!running)return;if(paused){raf=requestAnimationFrame(tick);return}if(invasionWarning){if(Date.now()>=invasionWarningUntil)invasionWarning=false}else{spawnClock-=1/60;if(!invasionWarningShown&&spawned===0&&spawnClock<=5&&spawnClock>0){spawnClock=5;invasionWarning=true;invasionWarningShown=true;invasionWarningUntil=Date.now()+2500}}if(spawned<toSpawn&&spawnClock<=0){spawn();spawned++;spawnClock=Math.max(2.2,5-wave*.1)} heroes.slice().forEach(h=>{h.cd-=1/60;const target=closestEnemy(h);const canAct=h.kind!=='moss'&&((h.kind==='luma')||Boolean(target));if(h.cd<=0&&canAct){projectile(h,target!);h.cd=defs.find(d=>d.kind===h.kind)!.cooldown}});enemies.slice().forEach(e=>{if(e.hp<=0){killEnemy(e);return}if(Date.now()<e.stunUntil){e.el.classList.add('stunned');e.el.style.left=`${e.x}%`;return}e.el.classList.remove('stunned');const blocker=firstCannon(e),columnWidth=100/gridColumns;if(blocker&&e.x<=(blocker.col+1)*columnWidth){e.x=(blocker.col+1)*columnWidth;e.el.classList.add('chewing');hurtHero(blocker,e.bite/60);if(blocker.hp<=0){blocker.el.classList.add('destroyed');setTimeout(()=>blocker.el.remove(),180);heroes.splice(heroes.indexOf(blocker),1)}}else{e.el.classList.remove('chewing');e.x-=e.speed}e.el.style.left=`${e.x}%`;if(e.hp<=0){core-=20;e.el.remove();enemies.splice(enemies.indexOf(e),1);if(core<=0)lose()}});if(spawned>=toSpawn&&enemies.length===0)completeWave();updateAll();raf=requestAnimationFrame(tick)}
function completeWave(){if(!running)return;running=false;cancelAnimationFrame(raf);const boss=wave%3===0,final=wave===30;$('#rewardTitle').textContent=final?'Campaign Complete!':boss?'Boss Defeated!':'Wave Complete!';$('#rewardText').textContent=final?'You survived all 30 waves and destroyed the final Hive Colossus. Khepri-9 is safe.':boss?'The Hive Colossus has fallen. The next swarm will be even more dangerous.':'All aliens in this wave are gone. Collect credits, visit the shop, or prepare for the next wave.';$('#rewardCoins').textContent=`+${waveCoins}`;$('#rewardKills').textContent=String(kills);$('#nextWave').textContent=final?'RETURN HOME →':'PREPARE NEXT WAVE →';$('#saveNotice').textContent='Save your progress before leaving this screen.';$('#saveNotice').classList.remove('saved');show('intermission')}
function lose(){running=false;cancelAnimationFrame(raf);show('lose')}
function openCodex(kind:string){const data:Record<string,[string,string,string]>={guardians:['CANNON DATABASE','Pick the right cannon for every lane.','<div class="dossier-grid">'+defs.map(d=>`<article><b>${d.glyph} ${d.name}</b><span>${d.role}</span><p>${d.description}</p><small>${unlocked.includes(d.kind)?'READY TO PLACE':'ARMORY LOCKED'}</small></article>`).join('')+'</div>'],enemies:['ALIEN INTEL','Three alien types are attacking the base.','<div class="dossier-grid"><article><b>Riftling</b><span>SCOUT ALIEN</span><p>Small and quick. Easy to defeat, but dangerous in a group.</p><small>RECOVERY · 8 CREDITS</small></article><article><b>Carapace Brute</b><span>HEAVY ALIEN</span><p>Slow and strong with a hard shell. Use several cannons.</p><small>RECOVERY · 17 CREDITS</small></article><article><b>Void Skitter</b><span>FAST ALIEN</span><p>A fast alien that can rush through a weak lane.</p><small>RECOVERY · 13 CREDITS</small></article></div>'],story:['MISSION BRIEFING','Keep the beacon safe.','<div class="story-entry"><p>Aliens are attacking Base Khepri-9. The rescue ship can only find you if the beacon stays on.</p><p>Build cannons on the defense pads. Stop each alien to earn credits. Use credits to unlock stronger cannons.</p><div class="record">YOUR JOB: KEEP THE BEACON ALIVE UNTIL RESCUE ARRIVES.</div></div>']};const [over,title,content]=data[kind];$('#codexOverline').textContent=over;$('#codexTitle').textContent=title;$('#codexContent').innerHTML=content;show('codex')}
$('#startGame').onclick=startExpedition;$('#resumeGame').onclick=resumeExpedition;$('#quitGame').onclick=()=>{running=false;cancelAnimationFrame(raf);show('home')};$('#pauseBtn').onclick=()=>{paused=!paused;$('#pauseBtn').textContent=paused?'▶':'Ⅱ';hint(paused?'Garden paused':'Garden resumed')};$('#arena').onclick=e=>{const p=(e.target as HTMLElement).closest<HTMLButtonElement>('.plot');if(p)plant(+p.dataset.r!,+p.dataset.c!)};$('#unitPicker').onchange=e=>{const kind=(e.target as HTMLSelectElement).value as HeroKind;if(kind)selectUnit(kind)};document.querySelectorAll<HTMLButtonElement>('[data-codex]').forEach(b=>b.onclick=()=>openCodex(b.dataset.codex!));$('#openShop').onclick=()=>{shopReturn='home';show('shop')};$('#openShopAlt').onclick=()=>{shopReturn='home';show('shop')};$('#closeShop').onclick=()=>show(shopReturn);$('#closeCodex').onclick=()=>show('home');$('#waveHome').onclick=()=>show('home');$('#saveProgress').onclick=saveProgress;$('#rewardShop').onclick=()=>{shopReturn='intermission';show('shop')};$('#shopItems').onclick=e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-unlock]');if(!b)return;const d=defs.find(x=>x.kind===b.dataset.unlock)!;if(coins<(d.unlock||0))return hint('Keep defending to earn more coins.');coins-=d.unlock!;unlocked.push(d.kind);save();renderCards();updateAll()};$('#nextWave').onclick=()=>{if(wave===30)show('home');else{wave++;startWave()}};$('#tryAgain').onclick=startWave;$('#returnHome').onclick=()=>show('home');renderCards();updateAll()
